apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-gitops-pipeline
spec:
  params:
    - default: >-
        image-registry.openshift-image-registry.svc:5000/dev-nm/spring-was-lib:latest
      name: docker-image
      type: string
    - name: url
      type: string
    - name: path-to-deployment-template
      type: string
    - name: path-to-deployment
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: master
        - name: submodules
          value: "true"
        - name: depth
          value: "1"
        - name: sslVerify
          value: "false"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
    - name: build
      params:
        - name: docker-image
          value: $(params.docker-image)
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah-pvc-task
      workspaces:
        - name: output
          workspace: git-source
    - name: gitops
      params:
        - name: docker-image
          value: $(params.docker-image)
        - name: path-to-deployment-template
          value: $(params.path-to-deployment-template)
        - name: path-to-deployment
          value: $(params.path-to-deployment)
      runAfter:
        - build
      taskRef:
        kind: Task
        name: gitops-pvc-task
      workspaces:
        - name: output
          workspace: git-source
  workspaces:
    - description: The git repo
      name: git-source
