apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-spring-boot
  labels:
    app: liberty-spring-boot
spec:
  selector:
    matchLabels:
      app: liberty-spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: liberty-spring-boot
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/dev-nm/spring-was-lib:123
          ports:
            - containerPort: 9080
